name: check-branch-name
run-name: Check branch name
on: 
  pull_request:
    types: [opened, reopened]
jobs:
  check-branch-name-valid:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "$GITHUB_REF"
        # if [[ ${{ github.ref}} == *"My long"* ]]; then
        #   echo "It's there!"
        # fi
      