name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions ${{ github.run_number }} for ${{ github.repository }}@${{ github.repository_id }}
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: yarn && yarn build